services:
  phantomjs-lambda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phantomjs-lambda
    platform: linux/amd64
    ports:
      - "9000:8080"
    environment:
      - AWS_LAMBDA_FUNCTION_HANDLER=src/index.handler